### PR TITLE
Improve README (#722)

### PR DESCRIPTION
**Pull request by barrybecker4**
Some fixes to the README based on https://docs.google.com/document/d/1Ep7Xucqt-Y6OXiCO_LNOTwUep_DMgVfxy6V1Fg5AwzM/edit.

Also updated libx11 in the ui docker file to avoid an error.

### CODE REVIEW

**Comment by ottomorac** [comment]
Thanks @barrybecker4 for the contribution. 

@x1m3 Please review the contribution. Barry has been interacting with me and Ram in one our client conversations. He has confirmed that the PR is now ready for review.

**Comment by guillermovahi** [comment]
@barrybecker4 can you please provide the tutorial mentioned on this doc (https://docs.google.com/document/d/1Ep7Xucqt-Y6OXiCO_LNOTwUep_DMgVfxy6V1Fg5AwzM/edit) where it should be explained how to integrate PrivadoID SDK into a react app where a graduate student can apply for a job on the platform?
Thanks in advance

**Comment by barrybecker4** [comment]
I can add a link to that doc in the README, but that doc contains nearly duplicate setup instructions. It would be nice to consolidate all the slightly different setup instructions into one source of truth.

**Comment by x1m3** [comment]
We are about to do a new release and there will be significant changes in the README file. We will consider your requests and try to include it. 

@barrybecker4  @guillermovahi

**Comment by barrybecker4** [comment]
@x1m3 @guillermovahi  I'm not sure if any of my changes were actually incorporated. For example
 - There are no additional instructions on how to use or configure ngrok or localtunnel.
 - The license link at the bottom is still broken.
 - Adding additional University credential demo link
 
 I will give the new instructions a try and see if they are any easier, but it would be nice if some of my suggestions could be incorporated.

**Comment by amonsosanz** [comment]
Hi @barrybecker4.

> There are no additional instructions on how to use or configure ngrok or localtunnel.

We do mention "use a tool like [Localtunnel](https://theboroer.github.io/localtunnel-www/) for testing purposes" in the readme. I don't think our readme should include a deeper level of detail. You can go to the documentation of these tools to get the details on how to use them. Also, these third-party tools, if ever used, should be used only in the testing phase, never in production. I fear that giving them more relevance in the readme could mislead some inexperienced users. But it's my opinion, you might be right. Also, mention that we have [this guide in our FAQ](https://docs.privado.id/docs/faqs/content/issuer-node-qr-code-callback-url-configuration). Maybe we can link it emphasizing that it should be only used for testing? By the way, I have just opened [a PR to update that guide](https://github.com/0xPolygonID/docs/pull/209) that became obsolete after this release.

> The license link at the bottom is still broken.

This was fixed [here](https://github.com/0xPolygonID/issuer-node/commit/a874070459c9821db4c99a72502eba434bf6892f). You can see the fix [in the develop branch](https://github.com/0xPolygonID/issuer-node/tree/develop).

> Adding additional University credential demo link

I guess we can add that link.

**Pull request closed without merging**
