### PR TITLE
chore: Add execution permission to UI deploy script

### PR DESCRIPTION
**Pull request by amonsosanz**
This PR adds execution permissions to `/app/scripts/deploy.sh` to fix this deploying issue:

```shell
$ docker logs issuer-ui-1

> sh-id-issuer-ui@1.0.0 build
> vite build

vite v4.1.1 building for production...
transforming...
✓ 3880 modules transformed.
rendering chunks...
computing gzip size...
dist/assets/check-57dd247b.svg                     0.22 kB
dist/assets/chevron-down-3baa8997.svg              0.22 kB
dist/assets/arrow-narrow-left-01cd4999.svg         0.23 kB
dist/assets/arrow-narrow-right-cc96bef9.svg        0.23 kB
dist/assets/alert-circle-792bde40.svg              0.34 kB
dist/assets/search-lg-2fd683df.svg                 0.34 kB
dist/assets/refresh-ccw-01-21526598.svg            0.38 kB
dist/assets/upload-01-7936670a.svg                 0.47 kB
dist/index.html                                    0.51 kB
dist/assets/credit-card-plus-0b18d088.svg          0.58 kB
dist/assets/link-external-01-849ca8db.svg          0.58 kB
dist/assets/credit-card-refresh-03ddcb57.svg       0.73 kB
dist/assets/file-search-02-8ed082dd.svg            0.73 kB
dist/assets/dots-vertical-8c61272e.svg             0.75 kB
dist/assets/folder-1462ae0f.svg                    0.82 kB
dist/assets/file-04-7a30fda2.svg                   0.97 kB
dist/assets/link-03-20ccb404.svg                   1.01 kB
dist/assets/file-05-b5439097.svg                   1.01 kB
dist/assets/copy-01-73b751c1.svg                   1.02 kB
dist/assets/message-smile-square-38dbda73.svg      1.32 kB
dist/assets/qr-code-72a0c25b.svg                   1.71 kB
dist/assets/polygonid-logo-b9dda384.svg            4.50 kB
dist/assets/index-7265d102.css                     3.92 kB │ gzip:   1.35 kB
dist/assets/index-48e1e044.js                  2,157.55 kB │ gzip: 694.28 kB

(!) Some chunks are larger than 500 kBs after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/configuration-options/#output-manualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
user-ui
password-ui
Adding password for user user-ui
user-ui:$apr1$hI/bq60g$dvp2Sr0RW0dff4VzA7lo21
2023/03/31 10:27:55 [notice] 64#64: using the "epoll" event method
2023/03/31 10:27:55 [notice] 64#64: nginx/1.23.4
2023/03/31 10:27:55 [notice] 64#64: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
2023/03/31 10:27:55 [notice] 64#64: OS: Linux 5.15.49-linuxkit
2023/03/31 10:27:55 [notice] 64#64: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2023/03/31 10:27:55 [notice] 64#64: start worker processes
2023/03/31 10:27:55 [notice] 64#64: start worker process 65
2023/03/31 10:27:55 [notice] 64#64: start worker process 66
2023/03/31 10:27:55 [notice] 64#64: start worker process 67
2023/03/31 10:27:55 [notice] 64#64: start worker process 68
2023/03/31 10:27:55 [notice] 64#64: start worker process 69
/bin/sh: can't open '/app/scripts/deploy.sh': No such file or directory
```

### CODE REVIEW

**Review by adrifdez — APPROVED** [review]

**Comment by cneuro** [comment]
Why is this needed?

**Comment by amonsosanz** [comment]
> Why is this needed?

Description added.

**Comment by amonsosanz** [comment]
@cneuro asked me to merge this with one approval, he will approve it later (not at the computer right now)

**Review by cneuro — COMMENTED** [review]
Approved

**Pull request merged**
