### PR TITLE
feat: Support custom networks

### PR DESCRIPTION
**Pull request by ilya-korotya**

### CODE REVIEW

**Review by x1m3 — COMMENTED** [review]
Please, change the title of the PR adding the prefix "feat:". This way, it will be reflected in the release note as a new feature.

(https://www.conventionalcommits.org/en/v1.0.0/)

**Review by martinsaporiti — APPROVED** [review]
LGTM

**Review by vmidyllic — APPROVED** [review]

**Review by javip97 — APPROVED** [review]
LGTM

**Review by x1m3 — APPROVED** [review]
LGTM!

**Review by vmidyllic — APPROVED** [review]

**Pull request merged**
